//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLTTCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talent
    {
        public int TalentId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Reknown { get; set; }
        public string Bio { get; set; }
        public string Image { get; set; }
        public int Status { get; set; }
        public string Email { get; set; }
    }
}
